<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');

// get quote items collection
$itemsCollection = $cart->getQuote()->getItemsCollection();

// get array of all items what can be display directly
$itemsVisible = $cart->getQuote()->getAllVisibleItems();

// get quote items array
$items = $cart->getQuote()->getAllItems();

foreach($items as $item) {
echo 'ID: '.$item->getProductId().'<br />';
echo 'Name: '.$item->getName().'<br />';
echo 'Sku: '.$item->getSku().'<br />';
echo 'Quantity: '.$item->getQty().'<br />';
echo 'Price: '.$item->getPrice().'<br />';
echo "<br />";
}

?>
<p>add an item to the cart and come back here if theres no data above</p>
<p>the console log will tell you how many items you have in the cart</p>

<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {

        var cart = customerData.get('cart');
        var count = cart().summary_count;

        cart.subscribe(function () {
            if (cart().summary_count !== count) {
                count = cart().summary_count;
                // do something here
                console.log('Number of items in cart is now: ' + count);
            }
        });
    });
</script>
